name: authentication-service

services:
  authservice:
    container_name: authservice
    build: .
    ports:
      - "4000:4000"
    env_file:
      - .env.production  # Use .env.production for prod
    volumes:
        - .:/app
        - /app/node_modules
    command: npm run start   # Run the production build
    depends_on:
      - authServiceDatabase
    restart: always  # Automatically restart the service on failure

  authServiceDatabase:
    image: mongo:latest
    container_name: db
    ports:
      - "27018:27017"
    volumes:
      - mongodb-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=authApp
      - MONGO_INITDB_ROOT_PASSWORD=authServicePassword
      - MONGO_INITDB_DATABASE=authservice_db

volumes:
  mongodb-data:
